package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi010Emisor generated by hbm2java
 */
@Entity
@Table(name = "TSI010_EMISOR")
public class Emisor implements java.io.Serializable {

	private BigDecimal cdIdemisor;
	private String nbNomEmisor;
	private String tpRating;
	private BigDecimal imPasivo;
	private BigDecimal tpTipemisor;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;
	private Character stEstado;
	private Set tsi011Limitesemisors = new HashSet(0);
	private Set tsi012Limfondoespecies = new HashSet(0);

	public Emisor() {
	}

	public Emisor(BigDecimal cdIdemisor) {
		this.cdIdemisor = cdIdemisor;
	}

	public Emisor(BigDecimal cdIdemisor, String nbNomEmisor,
			String tpRating, BigDecimal imPasivo, BigDecimal tpTipemisor,
			Date fhFecCreacion, String cdUsuCreacion, Date fhFecModifica,
			String cdUsuModifica, Date fhFecElimina, String cdUsuElimina,
			Character stEstado, Set tsi011Limitesemisors,
			Set tsi012Limfondoespecies) {
		this.cdIdemisor = cdIdemisor;
		this.nbNomEmisor = nbNomEmisor;
		this.tpRating = tpRating;
		this.imPasivo = imPasivo;
		this.tpTipemisor = tpTipemisor;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
		this.stEstado = stEstado;
		this.tsi011Limitesemisors = tsi011Limitesemisors;
		this.tsi012Limfondoespecies = tsi012Limfondoespecies;
	}

	@Id
	@Column(name = "CD_IDEMISOR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdemisor() {
		return this.cdIdemisor;
	}

	public void setCdIdemisor(BigDecimal cdIdemisor) {
		this.cdIdemisor = cdIdemisor;
	}

	@Column(name = "NB_NOM_EMISOR", length = 60)
	public String getNbNomEmisor() {
		return this.nbNomEmisor;
	}

	public void setNbNomEmisor(String nbNomEmisor) {
		this.nbNomEmisor = nbNomEmisor;
	}

	@Column(name = "TP_RATING", length = 3)
	public String getTpRating() {
		return this.tpRating;
	}

	public void setTpRating(String tpRating) {
		this.tpRating = tpRating;
	}

	@Column(name = "IM_PASIVO", precision = 22, scale = 0)
	public BigDecimal getImPasivo() {
		return this.imPasivo;
	}

	public void setImPasivo(BigDecimal imPasivo) {
		this.imPasivo = imPasivo;
	}

	@Column(name = "TP_TIPEMISOR", precision = 22, scale = 0)
	public BigDecimal getTpTipemisor() {
		return this.tpTipemisor;
	}

	public void setTpTipemisor(BigDecimal tpTipemisor) {
		this.tpTipemisor = tpTipemisor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tsi010Emisor")
	public Set getTsi011Limitesemisors() {
		return this.tsi011Limitesemisors;
	}

	public void setTsi011Limitesemisors(Set tsi011Limitesemisors) {
		this.tsi011Limitesemisors = tsi011Limitesemisors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tsi010Emisor")
	public Set getTsi012Limfondoespecies() {
		return this.tsi012Limfondoespecies;
	}

	public void setTsi012Limfondoespecies(Set tsi012Limfondoespecies) {
		this.tsi012Limfondoespecies = tsi012Limfondoespecies;
	}

}
