package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi005General generated by hbm2java
 */
@Entity
@Table(name = "TSI005_GENERAL")
public class General implements java.io.Serializable {

	private BigDecimal cdIdgeneral;
	private String nbDominio;
	private String nbDescGeneral;
	private String nbValorGeneral;
	private Character stEstado;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;
	private Set tsi012Limfondoespecies = new HashSet(0);

	public General() {
	}

	public General(BigDecimal cdIdgeneral) {
		this.cdIdgeneral = cdIdgeneral;
	}

	public General(BigDecimal cdIdgeneral, String nbDominio,
			String nbDescGeneral, String nbValorGeneral, Character stEstado,
			Date fhFecCreacion, String cdUsuCreacion, Date fhFecModifica,
			String cdUsuModifica, Date fhFecElimina, String cdUsuElimina,
			Set tsi012Limfondoespecies) {
		this.cdIdgeneral = cdIdgeneral;
		this.nbDominio = nbDominio;
		this.nbDescGeneral = nbDescGeneral;
		this.nbValorGeneral = nbValorGeneral;
		this.stEstado = stEstado;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
		this.tsi012Limfondoespecies = tsi012Limfondoespecies;
	}

	@Id
	@Column(name = "CD_IDGENERAL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdgeneral() {
		return this.cdIdgeneral;
	}

	public void setCdIdgeneral(BigDecimal cdIdgeneral) {
		this.cdIdgeneral = cdIdgeneral;
	}

	@Column(name = "NB_DOMINIO", length = 30)
	public String getNbDominio() {
		return this.nbDominio;
	}

	public void setNbDominio(String nbDominio) {
		this.nbDominio = nbDominio;
	}

	@Column(name = "NB_DESC_GENERAL", length = 60)
	public String getNbDescGeneral() {
		return this.nbDescGeneral;
	}

	public void setNbDescGeneral(String nbDescGeneral) {
		this.nbDescGeneral = nbDescGeneral;
	}

	@Column(name = "NB_VALOR_GENERAL", length = 40)
	public String getNbValorGeneral() {
		return this.nbValorGeneral;
	}

	public void setNbValorGeneral(String nbValorGeneral) {
		this.nbValorGeneral = nbValorGeneral;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tsi005General")
	public Set getTsi012Limfondoespecies() {
		return this.tsi012Limfondoespecies;
	}

	public void setTsi012Limfondoespecies(Set tsi012Limfondoespecies) {
		this.tsi012Limfondoespecies = tsi012Limfondoespecies;
	}

}
