package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi002Infoport generated by hbm2java
 */
@Entity
@Table(name = "TSI002_INFOPORT")
public class Infoport implements java.io.Serializable {

	private BigDecimal cdIdinfoport;
	private String nbNomFondo;
	private Character tpTipfondo;
	private String nbNomEmisor;
	private String tpRatingEmisor;
	private String nbEspecie;
	private Date fhFecEmision;
	private Date fhFecVencimiento;
	private BigDecimal imNominalEnMil;
	private BigDecimal imCupon;
	private Date fhFecUltCupon;
	private Character tpModalidad;
	private BigDecimal imPrecioLimpio;
	private BigDecimal imPrecioSucio;
	private BigDecimal imValorSinInter;
	private BigDecimal imInteresCorrid;
	private BigDecimal imValorMonRef;
	private String tpAbrevMoneda;
	private BigDecimal imValorMonLocal;
	private BigDecimal imTotCtasCobrar;
	private BigDecimal imTotCtasPagar;
	private BigDecimal nuPeriodo;
	private BigDecimal imYtm;
	private BigDecimal imDuracNorm;
	private BigDecimal imDuracModif;
	private String tpClasifica;
	private BigDecimal imPrecioAct;
	private BigDecimal imPrecCom;
	private String nbIsim;
	private String nbMnemoniaco;
	private BigDecimal nuNumDiasVcto;
	private Date fhFecvctoSgtCup;
	private Date fhFecUltOperac;
	private BigDecimal imDuracNorLibor;
	private BigDecimal imCompraTMasN;
	private String nbObservacion;
	private BigDecimal imValorPorDurac;
	private BigDecimal imValorPorYtm;
	private BigDecimal nuDiaParaVenc;
	private String stEstado;
	private Character stCondicion;

	public Infoport() {
	}

	public Infoport(BigDecimal cdIdinfoport) {
		this.cdIdinfoport = cdIdinfoport;
	}

	public Infoport(BigDecimal cdIdinfoport, String nbNomFondo,
			Character tpTipfondo, String nbNomEmisor, String tpRatingEmisor,
			String nbEspecie, Date fhFecEmision, Date fhFecVencimiento,
			BigDecimal imNominalEnMil, BigDecimal imCupon, Date fhFecUltCupon,
			Character tpModalidad, BigDecimal imPrecioLimpio,
			BigDecimal imPrecioSucio, BigDecimal imValorSinInter,
			BigDecimal imInteresCorrid, BigDecimal imValorMonRef,
			String tpAbrevMoneda, BigDecimal imValorMonLocal,
			BigDecimal imTotCtasCobrar, BigDecimal imTotCtasPagar,
			BigDecimal nuPeriodo, BigDecimal imYtm, BigDecimal imDuracNorm,
			BigDecimal imDuracModif, String tpClasifica,
			BigDecimal imPrecioAct, BigDecimal imPrecCom, String nbIsim,
			String nbMnemoniaco, BigDecimal nuNumDiasVcto,
			Date fhFecvctoSgtCup, Date fhFecUltOperac,
			BigDecimal imDuracNorLibor, BigDecimal imCompraTMasN,
			String nbObservacion, BigDecimal imValorPorDurac,
			BigDecimal imValorPorYtm, BigDecimal nuDiaParaVenc,
			String stEstado, Character stCondicion) {
		this.cdIdinfoport = cdIdinfoport;
		this.nbNomFondo = nbNomFondo;
		this.tpTipfondo = tpTipfondo;
		this.nbNomEmisor = nbNomEmisor;
		this.tpRatingEmisor = tpRatingEmisor;
		this.nbEspecie = nbEspecie;
		this.fhFecEmision = fhFecEmision;
		this.fhFecVencimiento = fhFecVencimiento;
		this.imNominalEnMil = imNominalEnMil;
		this.imCupon = imCupon;
		this.fhFecUltCupon = fhFecUltCupon;
		this.tpModalidad = tpModalidad;
		this.imPrecioLimpio = imPrecioLimpio;
		this.imPrecioSucio = imPrecioSucio;
		this.imValorSinInter = imValorSinInter;
		this.imInteresCorrid = imInteresCorrid;
		this.imValorMonRef = imValorMonRef;
		this.tpAbrevMoneda = tpAbrevMoneda;
		this.imValorMonLocal = imValorMonLocal;
		this.imTotCtasCobrar = imTotCtasCobrar;
		this.imTotCtasPagar = imTotCtasPagar;
		this.nuPeriodo = nuPeriodo;
		this.imYtm = imYtm;
		this.imDuracNorm = imDuracNorm;
		this.imDuracModif = imDuracModif;
		this.tpClasifica = tpClasifica;
		this.imPrecioAct = imPrecioAct;
		this.imPrecCom = imPrecCom;
		this.nbIsim = nbIsim;
		this.nbMnemoniaco = nbMnemoniaco;
		this.nuNumDiasVcto = nuNumDiasVcto;
		this.fhFecvctoSgtCup = fhFecvctoSgtCup;
		this.fhFecUltOperac = fhFecUltOperac;
		this.imDuracNorLibor = imDuracNorLibor;
		this.imCompraTMasN = imCompraTMasN;
		this.nbObservacion = nbObservacion;
		this.imValorPorDurac = imValorPorDurac;
		this.imValorPorYtm = imValorPorYtm;
		this.nuDiaParaVenc = nuDiaParaVenc;
		this.stEstado = stEstado;
		this.stCondicion = stCondicion;
	}

	@Id
	@Column(name = "CD_IDINFOPORT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdinfoport() {
		return this.cdIdinfoport;
	}

	public void setCdIdinfoport(BigDecimal cdIdinfoport) {
		this.cdIdinfoport = cdIdinfoport;
	}

	@Column(name = "NB_NOM_FONDO", length = 40)
	public String getNbNomFondo() {
		return this.nbNomFondo;
	}

	public void setNbNomFondo(String nbNomFondo) {
		this.nbNomFondo = nbNomFondo;
	}

	@Column(name = "TP_TIPFONDO", length = 1)
	public Character getTpTipfondo() {
		return this.tpTipfondo;
	}

	public void setTpTipfondo(Character tpTipfondo) {
		this.tpTipfondo = tpTipfondo;
	}

	@Column(name = "NB_NOM_EMISOR", length = 60)
	public String getNbNomEmisor() {
		return this.nbNomEmisor;
	}

	public void setNbNomEmisor(String nbNomEmisor) {
		this.nbNomEmisor = nbNomEmisor;
	}

	@Column(name = "TP_RATING_EMISOR", length = 4)
	public String getTpRatingEmisor() {
		return this.tpRatingEmisor;
	}

	public void setTpRatingEmisor(String tpRatingEmisor) {
		this.tpRatingEmisor = tpRatingEmisor;
	}

	@Column(name = "NB_ESPECIE", length = 40)
	public String getNbEspecie() {
		return this.nbEspecie;
	}

	public void setNbEspecie(String nbEspecie) {
		this.nbEspecie = nbEspecie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_EMISION", length = 7)
	public Date getFhFecEmision() {
		return this.fhFecEmision;
	}

	public void setFhFecEmision(Date fhFecEmision) {
		this.fhFecEmision = fhFecEmision;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_VENCIMIENTO", length = 7)
	public Date getFhFecVencimiento() {
		return this.fhFecVencimiento;
	}

	public void setFhFecVencimiento(Date fhFecVencimiento) {
		this.fhFecVencimiento = fhFecVencimiento;
	}

	@Column(name = "IM_NOMINAL_EN_MIL", precision = 22, scale = 0)
	public BigDecimal getImNominalEnMil() {
		return this.imNominalEnMil;
	}

	public void setImNominalEnMil(BigDecimal imNominalEnMil) {
		this.imNominalEnMil = imNominalEnMil;
	}

	@Column(name = "IM_CUPON", precision = 22, scale = 0)
	public BigDecimal getImCupon() {
		return this.imCupon;
	}

	public void setImCupon(BigDecimal imCupon) {
		this.imCupon = imCupon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ULT_CUPON", length = 7)
	public Date getFhFecUltCupon() {
		return this.fhFecUltCupon;
	}

	public void setFhFecUltCupon(Date fhFecUltCupon) {
		this.fhFecUltCupon = fhFecUltCupon;
	}

	@Column(name = "TP_MODALIDAD", length = 1)
	public Character getTpModalidad() {
		return this.tpModalidad;
	}

	public void setTpModalidad(Character tpModalidad) {
		this.tpModalidad = tpModalidad;
	}

	@Column(name = "IM_PRECIO_LIMPIO", precision = 22, scale = 0)
	public BigDecimal getImPrecioLimpio() {
		return this.imPrecioLimpio;
	}

	public void setImPrecioLimpio(BigDecimal imPrecioLimpio) {
		this.imPrecioLimpio = imPrecioLimpio;
	}

	@Column(name = "IM_PRECIO_SUCIO", precision = 22, scale = 0)
	public BigDecimal getImPrecioSucio() {
		return this.imPrecioSucio;
	}

	public void setImPrecioSucio(BigDecimal imPrecioSucio) {
		this.imPrecioSucio = imPrecioSucio;
	}

	@Column(name = "IM_VALOR_SIN_INTER", precision = 22, scale = 0)
	public BigDecimal getImValorSinInter() {
		return this.imValorSinInter;
	}

	public void setImValorSinInter(BigDecimal imValorSinInter) {
		this.imValorSinInter = imValorSinInter;
	}

	@Column(name = "IM_INTERES_CORRID", precision = 22, scale = 0)
	public BigDecimal getImInteresCorrid() {
		return this.imInteresCorrid;
	}

	public void setImInteresCorrid(BigDecimal imInteresCorrid) {
		this.imInteresCorrid = imInteresCorrid;
	}

	@Column(name = "IM_VALOR_MON_REF", precision = 22, scale = 0)
	public BigDecimal getImValorMonRef() {
		return this.imValorMonRef;
	}

	public void setImValorMonRef(BigDecimal imValorMonRef) {
		this.imValorMonRef = imValorMonRef;
	}

	@Column(name = "TP_ABREV_MONEDA", length = 3)
	public String getTpAbrevMoneda() {
		return this.tpAbrevMoneda;
	}

	public void setTpAbrevMoneda(String tpAbrevMoneda) {
		this.tpAbrevMoneda = tpAbrevMoneda;
	}

	@Column(name = "IM_VALOR_MON_LOCAL", precision = 22, scale = 0)
	public BigDecimal getImValorMonLocal() {
		return this.imValorMonLocal;
	}

	public void setImValorMonLocal(BigDecimal imValorMonLocal) {
		this.imValorMonLocal = imValorMonLocal;
	}

	@Column(name = "IM_TOT_CTAS_COBRAR", precision = 22, scale = 0)
	public BigDecimal getImTotCtasCobrar() {
		return this.imTotCtasCobrar;
	}

	public void setImTotCtasCobrar(BigDecimal imTotCtasCobrar) {
		this.imTotCtasCobrar = imTotCtasCobrar;
	}

	@Column(name = "IM_TOT_CTAS_PAGAR", precision = 22, scale = 0)
	public BigDecimal getImTotCtasPagar() {
		return this.imTotCtasPagar;
	}

	public void setImTotCtasPagar(BigDecimal imTotCtasPagar) {
		this.imTotCtasPagar = imTotCtasPagar;
	}

	@Column(name = "NU_PERIODO", precision = 22, scale = 0)
	public BigDecimal getNuPeriodo() {
		return this.nuPeriodo;
	}

	public void setNuPeriodo(BigDecimal nuPeriodo) {
		this.nuPeriodo = nuPeriodo;
	}

	@Column(name = "IM_YTM", precision = 22, scale = 0)
	public BigDecimal getImYtm() {
		return this.imYtm;
	}

	public void setImYtm(BigDecimal imYtm) {
		this.imYtm = imYtm;
	}

	@Column(name = "IM_DURAC_NORM", precision = 22, scale = 0)
	public BigDecimal getImDuracNorm() {
		return this.imDuracNorm;
	}

	public void setImDuracNorm(BigDecimal imDuracNorm) {
		this.imDuracNorm = imDuracNorm;
	}

	@Column(name = "IM_DURAC_MODIF", precision = 22, scale = 0)
	public BigDecimal getImDuracModif() {
		return this.imDuracModif;
	}

	public void setImDuracModif(BigDecimal imDuracModif) {
		this.imDuracModif = imDuracModif;
	}

	@Column(name = "TP_CLASIFICA", length = 6)
	public String getTpClasifica() {
		return this.tpClasifica;
	}

	public void setTpClasifica(String tpClasifica) {
		this.tpClasifica = tpClasifica;
	}

	@Column(name = "IM_PRECIO_ACT", precision = 22, scale = 0)
	public BigDecimal getImPrecioAct() {
		return this.imPrecioAct;
	}

	public void setImPrecioAct(BigDecimal imPrecioAct) {
		this.imPrecioAct = imPrecioAct;
	}

	@Column(name = "IM_PREC_COM", precision = 22, scale = 0)
	public BigDecimal getImPrecCom() {
		return this.imPrecCom;
	}

	public void setImPrecCom(BigDecimal imPrecCom) {
		this.imPrecCom = imPrecCom;
	}

	@Column(name = "NB_ISIM", length = 15)
	public String getNbIsim() {
		return this.nbIsim;
	}

	public void setNbIsim(String nbIsim) {
		this.nbIsim = nbIsim;
	}

	@Column(name = "NB_MNEMONIACO", length = 15)
	public String getNbMnemoniaco() {
		return this.nbMnemoniaco;
	}

	public void setNbMnemoniaco(String nbMnemoniaco) {
		this.nbMnemoniaco = nbMnemoniaco;
	}

	@Column(name = "NU_NUM_DIAS_VCTO", precision = 22, scale = 0)
	public BigDecimal getNuNumDiasVcto() {
		return this.nuNumDiasVcto;
	}

	public void setNuNumDiasVcto(BigDecimal nuNumDiasVcto) {
		this.nuNumDiasVcto = nuNumDiasVcto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FECVCTO_SGT_CUP", length = 7)
	public Date getFhFecvctoSgtCup() {
		return this.fhFecvctoSgtCup;
	}

	public void setFhFecvctoSgtCup(Date fhFecvctoSgtCup) {
		this.fhFecvctoSgtCup = fhFecvctoSgtCup;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ULT_OPERAC", length = 7)
	public Date getFhFecUltOperac() {
		return this.fhFecUltOperac;
	}

	public void setFhFecUltOperac(Date fhFecUltOperac) {
		this.fhFecUltOperac = fhFecUltOperac;
	}

	@Column(name = "IM_DURAC_NOR_LIBOR", precision = 22, scale = 0)
	public BigDecimal getImDuracNorLibor() {
		return this.imDuracNorLibor;
	}

	public void setImDuracNorLibor(BigDecimal imDuracNorLibor) {
		this.imDuracNorLibor = imDuracNorLibor;
	}

	@Column(name = "IM_COMPRA_T_MAS_N", precision = 22, scale = 0)
	public BigDecimal getImCompraTMasN() {
		return this.imCompraTMasN;
	}

	public void setImCompraTMasN(BigDecimal imCompraTMasN) {
		this.imCompraTMasN = imCompraTMasN;
	}

	@Column(name = "NB_OBSERVACION", length = 100)
	public String getNbObservacion() {
		return this.nbObservacion;
	}

	public void setNbObservacion(String nbObservacion) {
		this.nbObservacion = nbObservacion;
	}

	@Column(name = "IM_VALOR_POR_DURAC", precision = 22, scale = 0)
	public BigDecimal getImValorPorDurac() {
		return this.imValorPorDurac;
	}

	public void setImValorPorDurac(BigDecimal imValorPorDurac) {
		this.imValorPorDurac = imValorPorDurac;
	}

	@Column(name = "IM_VALOR_POR_YTM", precision = 22, scale = 0)
	public BigDecimal getImValorPorYtm() {
		return this.imValorPorYtm;
	}

	public void setImValorPorYtm(BigDecimal imValorPorYtm) {
		this.imValorPorYtm = imValorPorYtm;
	}

	@Column(name = "NU_DIA_PARA_VENC", precision = 22, scale = 0)
	public BigDecimal getNuDiaParaVenc() {
		return this.nuDiaParaVenc;
	}

	public void setNuDiaParaVenc(BigDecimal nuDiaParaVenc) {
		this.nuDiaParaVenc = nuDiaParaVenc;
	}

	@Column(name = "ST_ESTADO", length = 9)
	public String getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(String stEstado) {
		this.stEstado = stEstado;
	}

	@Column(name = "ST_CONDICION", length = 1)
	public Character getStCondicion() {
		return this.stCondicion;
	}

	public void setStCondicion(Character stCondicion) {
		this.stCondicion = stCondicion;
	}

}
