package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi012Limfondoespecie generated by hbm2java
 */
@Entity
@Table(name = "TSI012_LIMFONDOESPECIE")
public class LimFondoEspecie implements java.io.Serializable {

	private BigDecimal cdIdconfiguracion;
	private Emisor tsi010Emisor;
	private Fondo tsi008Fondo;
	private General tsi005General;
	private BigDecimal pcPorcIni;
	private BigDecimal pcPorcFin;
	private BigDecimal nuMontoIni;
	private BigDecimal nuMontoFin;
	private Character stEstado;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;

	public LimFondoEspecie() {
	}

	public LimFondoEspecie(BigDecimal cdIdconfiguracion,
			Emisor tsi010Emisor, Fondo tsi008Fondo,
			General tsi005General) {
		this.cdIdconfiguracion = cdIdconfiguracion;
		this.tsi010Emisor = tsi010Emisor;
		this.tsi008Fondo = tsi008Fondo;
		this.tsi005General = tsi005General;
	}

	public LimFondoEspecie(BigDecimal cdIdconfiguracion,
			Emisor tsi010Emisor, Fondo tsi008Fondo,
			General tsi005General, BigDecimal pcPorcIni,
			BigDecimal pcPorcFin, BigDecimal nuMontoIni, BigDecimal nuMontoFin,
			Character stEstado, Date fhFecCreacion, String cdUsuCreacion,
			Date fhFecModifica, String cdUsuModifica, Date fhFecElimina,
			String cdUsuElimina) {
		this.cdIdconfiguracion = cdIdconfiguracion;
		this.tsi010Emisor = tsi010Emisor;
		this.tsi008Fondo = tsi008Fondo;
		this.tsi005General = tsi005General;
		this.pcPorcIni = pcPorcIni;
		this.pcPorcFin = pcPorcFin;
		this.nuMontoIni = nuMontoIni;
		this.nuMontoFin = nuMontoFin;
		this.stEstado = stEstado;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
	}

	@Id
	@Column(name = "CD_IDCONFIGURACION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdconfiguracion() {
		return this.cdIdconfiguracion;
	}

	public void setCdIdconfiguracion(BigDecimal cdIdconfiguracion) {
		this.cdIdconfiguracion = cdIdconfiguracion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_IDEMISOR", nullable = false)
	public Emisor getTsi010Emisor() {
		return this.tsi010Emisor;
	}

	public void setTsi010Emisor(Emisor tsi010Emisor) {
		this.tsi010Emisor = tsi010Emisor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_IDFONDO", nullable = false)
	public Fondo getTsi008Fondo() {
		return this.tsi008Fondo;
	}

	public void setTsi008Fondo(Fondo tsi008Fondo) {
		this.tsi008Fondo = tsi008Fondo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_IDGENERAL", nullable = false)
	public General getTsi005General() {
		return this.tsi005General;
	}

	public void setTsi005General(General tsi005General) {
		this.tsi005General = tsi005General;
	}

	@Column(name = "PC_PORC_INI", precision = 22, scale = 0)
	public BigDecimal getPcPorcIni() {
		return this.pcPorcIni;
	}

	public void setPcPorcIni(BigDecimal pcPorcIni) {
		this.pcPorcIni = pcPorcIni;
	}

	@Column(name = "PC_PORC_FIN", precision = 22, scale = 0)
	public BigDecimal getPcPorcFin() {
		return this.pcPorcFin;
	}

	public void setPcPorcFin(BigDecimal pcPorcFin) {
		this.pcPorcFin = pcPorcFin;
	}

	@Column(name = "NU_MONTO_INI", precision = 22, scale = 0)
	public BigDecimal getNuMontoIni() {
		return this.nuMontoIni;
	}

	public void setNuMontoIni(BigDecimal nuMontoIni) {
		this.nuMontoIni = nuMontoIni;
	}

	@Column(name = "NU_MONTO_FIN", precision = 22, scale = 0)
	public BigDecimal getNuMontoFin() {
		return this.nuMontoFin;
	}

	public void setNuMontoFin(BigDecimal nuMontoFin) {
		this.nuMontoFin = nuMontoFin;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

}
