package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi011Limitesemisor generated by hbm2java
 */
@Entity
@Table(name = "TSI011_LIMITESEMISOR")
public class LimitesEmisor implements java.io.Serializable {

	private LimitesEmisorId id;
	private Emisor tsi010Emisor;
	private BigDecimal pcPorcIni;
	private BigDecimal pcPorcFin;
	private BigDecimal nuMontoIni;
	private BigDecimal nuMontoFin;
	private Character stEstado;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;

	public LimitesEmisor() {
	}

	public LimitesEmisor(LimitesEmisorId id,
			Emisor tsi010Emisor) {
		this.id = id;
		this.tsi010Emisor = tsi010Emisor;
	}

	public LimitesEmisor(LimitesEmisorId id,
			Emisor tsi010Emisor, BigDecimal pcPorcIni,
			BigDecimal pcPorcFin, BigDecimal nuMontoIni, BigDecimal nuMontoFin,
			Character stEstado, Date fhFecCreacion, String cdUsuCreacion,
			Date fhFecModifica, String cdUsuModifica, Date fhFecElimina,
			String cdUsuElimina) {
		this.id = id;
		this.tsi010Emisor = tsi010Emisor;
		this.pcPorcIni = pcPorcIni;
		this.pcPorcFin = pcPorcFin;
		this.nuMontoIni = nuMontoIni;
		this.nuMontoFin = nuMontoFin;
		this.stEstado = stEstado;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdIdlimite", column = @Column(name = "CD_IDLIMITE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdIdemisor", column = @Column(name = "CD_IDEMISOR", nullable = false, precision = 22, scale = 0)) })
	public LimitesEmisorId getId() {
		return this.id;
	}

	public void setId(LimitesEmisorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_IDEMISOR", nullable = false, insertable = false, updatable = false)
	public Emisor getTsi010Emisor() {
		return this.tsi010Emisor;
	}

	public void setTsi010Emisor(Emisor tsi010Emisor) {
		this.tsi010Emisor = tsi010Emisor;
	}

	@Column(name = "PC_PORC_INI", precision = 22, scale = 0)
	public BigDecimal getPcPorcIni() {
		return this.pcPorcIni;
	}

	public void setPcPorcIni(BigDecimal pcPorcIni) {
		this.pcPorcIni = pcPorcIni;
	}

	@Column(name = "PC_PORC_FIN", precision = 22, scale = 0)
	public BigDecimal getPcPorcFin() {
		return this.pcPorcFin;
	}

	public void setPcPorcFin(BigDecimal pcPorcFin) {
		this.pcPorcFin = pcPorcFin;
	}

	@Column(name = "NU_MONTO_INI", precision = 22, scale = 0)
	public BigDecimal getNuMontoIni() {
		return this.nuMontoIni;
	}

	public void setNuMontoIni(BigDecimal nuMontoIni) {
		this.nuMontoIni = nuMontoIni;
	}

	@Column(name = "NU_MONTO_FIN", precision = 22, scale = 0)
	public BigDecimal getNuMontoFin() {
		return this.nuMontoFin;
	}

	public void setNuMontoFin(BigDecimal nuMontoFin) {
		this.nuMontoFin = nuMontoFin;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

}
