package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Tsi011LimitesemisorId generated by hbm2java
 */
@Embeddable
public class LimitesEmisorId implements java.io.Serializable {

	private BigDecimal cdIdlimite;
	private BigDecimal cdIdemisor;

	public LimitesEmisorId() {
	}

	public LimitesEmisorId(BigDecimal cdIdlimite, BigDecimal cdIdemisor) {
		this.cdIdlimite = cdIdlimite;
		this.cdIdemisor = cdIdemisor;
	}

	@Column(name = "CD_IDLIMITE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdlimite() {
		return this.cdIdlimite;
	}

	public void setCdIdlimite(BigDecimal cdIdlimite) {
		this.cdIdlimite = cdIdlimite;
	}

	@Column(name = "CD_IDEMISOR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdemisor() {
		return this.cdIdemisor;
	}

	public void setCdIdemisor(BigDecimal cdIdemisor) {
		this.cdIdemisor = cdIdemisor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LimitesEmisorId))
			return false;
		LimitesEmisorId castOther = (LimitesEmisorId) other;

		return ((this.getCdIdlimite() == castOther.getCdIdlimite()) || (this
				.getCdIdlimite() != null && castOther.getCdIdlimite() != null && this
				.getCdIdlimite().equals(castOther.getCdIdlimite())))
				&& ((this.getCdIdemisor() == castOther.getCdIdemisor()) || (this
						.getCdIdemisor() != null
						&& castOther.getCdIdemisor() != null && this
						.getCdIdemisor().equals(castOther.getCdIdemisor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdIdlimite() == null ? 0 : this.getCdIdlimite()
						.hashCode());
		result = 37
				* result
				+ (getCdIdemisor() == null ? 0 : this.getCdIdemisor()
						.hashCode());
		return result;
	}

}
