package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi007Perfil generated by hbm2java
 */
@Entity
@Table(name = "TSI007_PERFIL")
public class Perfil implements java.io.Serializable {

	private BigDecimal cdIdperfil;
	private String nbMonPerfil;
	private Date fhFecInicio;
	private Date fhFecFin;
	private BigDecimal tpTipperfil;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;
	private Character stEstado;
	private Set tsi006Usuarios = new HashSet(0);
	private Set tsi009Perfilfondos = new HashSet(0);

	public Perfil() {
	}

	public Perfil(BigDecimal cdIdperfil) {
		this.cdIdperfil = cdIdperfil;
	}

	public Perfil(BigDecimal cdIdperfil, String nbMonPerfil,
			Date fhFecInicio, Date fhFecFin, BigDecimal tpTipperfil,
			Date fhFecCreacion, String cdUsuCreacion, Date fhFecModifica,
			String cdUsuModifica, Date fhFecElimina, String cdUsuElimina,
			Character stEstado, Set tsi006Usuarios, Set tsi009Perfilfondos) {
		this.cdIdperfil = cdIdperfil;
		this.nbMonPerfil = nbMonPerfil;
		this.fhFecInicio = fhFecInicio;
		this.fhFecFin = fhFecFin;
		this.tpTipperfil = tpTipperfil;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
		this.stEstado = stEstado;
		this.tsi006Usuarios = tsi006Usuarios;
		this.tsi009Perfilfondos = tsi009Perfilfondos;
	}

	@Id
	@Column(name = "CD_IDPERFIL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdperfil() {
		return this.cdIdperfil;
	}

	public void setCdIdperfil(BigDecimal cdIdperfil) {
		this.cdIdperfil = cdIdperfil;
	}

	@Column(name = "NB_MON_PERFIL", length = 40)
	public String getNbMonPerfil() {
		return this.nbMonPerfil;
	}

	public void setNbMonPerfil(String nbMonPerfil) {
		this.nbMonPerfil = nbMonPerfil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_INICIO", length = 7)
	public Date getFhFecInicio() {
		return this.fhFecInicio;
	}

	public void setFhFecInicio(Date fhFecInicio) {
		this.fhFecInicio = fhFecInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_FIN", length = 7)
	public Date getFhFecFin() {
		return this.fhFecFin;
	}

	public void setFhFecFin(Date fhFecFin) {
		this.fhFecFin = fhFecFin;
	}

	@Column(name = "TP_TIPPERFIL", precision = 22, scale = 0)
	public BigDecimal getTpTipperfil() {
		return this.tpTipperfil;
	}

	public void setTpTipperfil(BigDecimal tpTipperfil) {
		this.tpTipperfil = tpTipperfil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tsi007Perfil")
	public Set getTsi006Usuarios() {
		return this.tsi006Usuarios;
	}

	public void setTsi006Usuarios(Set tsi006Usuarios) {
		this.tsi006Usuarios = tsi006Usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tsi007Perfil")
	public Set getTsi009Perfilfondos() {
		return this.tsi009Perfilfondos;
	}

	public void setTsi009Perfilfondos(Set tsi009Perfilfondos) {
		this.tsi009Perfilfondos = tsi009Perfilfondos;
	}

}
