package com.pss.simulador.bs.domain;
// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Tsi009PerfilfondoId generated by hbm2java
 */
@Embeddable
public class PerfilFondoId implements java.io.Serializable {

	private BigDecimal cdIdperfil;
	private BigDecimal cdIdfondo;

	public PerfilFondoId() {
	}

	public PerfilFondoId(BigDecimal cdIdperfil, BigDecimal cdIdfondo) {
		this.cdIdperfil = cdIdperfil;
		this.cdIdfondo = cdIdfondo;
	}

	@Column(name = "CD_IDPERFIL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdperfil() {
		return this.cdIdperfil;
	}

	public void setCdIdperfil(BigDecimal cdIdperfil) {
		this.cdIdperfil = cdIdperfil;
	}

	@Column(name = "CD_IDFONDO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdfondo() {
		return this.cdIdfondo;
	}

	public void setCdIdfondo(BigDecimal cdIdfondo) {
		this.cdIdfondo = cdIdfondo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilFondoId))
			return false;
		PerfilFondoId castOther = (PerfilFondoId) other;

		return ((this.getCdIdperfil() == castOther.getCdIdperfil()) || (this
				.getCdIdperfil() != null && castOther.getCdIdperfil() != null && this
				.getCdIdperfil().equals(castOther.getCdIdperfil())))
				&& ((this.getCdIdfondo() == castOther.getCdIdfondo()) || (this
						.getCdIdfondo() != null
						&& castOther.getCdIdfondo() != null && this
						.getCdIdfondo().equals(castOther.getCdIdfondo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdIdperfil() == null ? 0 : this.getCdIdperfil()
						.hashCode());
		result = 37 * result
				+ (getCdIdfondo() == null ? 0 : this.getCdIdfondo().hashCode());
		return result;
	}

}
