package com.pss.simulador.bs.domain;

// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi009Perfilfondo generated by hbm2java
 */
@Entity
@Table(name = "TSI009_PERFILFONDO")
public class PerfilFondo implements java.io.Serializable {

	private PerfilFondoId id;
	private Fondo tsi008Fondo;
	private Perfil tsi007Perfil;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;
	private Character stEstado;

	public PerfilFondo() {
	}

	public PerfilFondo(PerfilFondoId id, Fondo tsi008Fondo,
			Perfil tsi007Perfil) {
		this.id = id;
		this.tsi008Fondo = tsi008Fondo;
		this.tsi007Perfil = tsi007Perfil;
	}

	public PerfilFondo(PerfilFondoId id, Fondo tsi008Fondo,
			Perfil tsi007Perfil, Date fhFecCreacion,
			String cdUsuCreacion, Date fhFecModifica, String cdUsuModifica,
			Date fhFecElimina, String cdUsuElimina, Character stEstado) {
		this.id = id;
		this.tsi008Fondo = tsi008Fondo;
		this.tsi007Perfil = tsi007Perfil;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
		this.stEstado = stEstado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdIdperfil", column = @Column(name = "CD_IDPERFIL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdIdfondo", column = @Column(name = "CD_IDFONDO", nullable = false, precision = 22, scale = 0)) })
	public PerfilFondoId getId() {
		return this.id;
	}

	public void setId(PerfilFondoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_IDFONDO", nullable = false, insertable = false, updatable = false)
	public Fondo getTsi008Fondo() {
		return this.tsi008Fondo;
	}

	public void setTsi008Fondo(Fondo tsi008Fondo) {
		this.tsi008Fondo = tsi008Fondo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_IDPERFIL", nullable = false, insertable = false, updatable = false)
	public Perfil getTsi007Perfil() {
		return this.tsi007Perfil;
	}

	public void setTsi007Perfil(Perfil tsi007Perfil) {
		this.tsi007Perfil = tsi007Perfil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

}
