package com.pss.simulador.bs.domain;
// default package
// Generated 31/01/2016 07:26:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Tsi016Procesocarga generated by hbm2java
 */
@Entity
@Table(name = "TSI016_PROCESOCARGA", schema="BBVATESOR")
public class ProcesoCarga implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer cdIdproceso;
	private Date fhFecIni;
	private Date fhFecFin;
	private BigDecimal nrRegLeido;
	private BigDecimal nrRegErrado;
	private String stEstadoProceso;
	private String stEstado;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;
	private Date fhFecImporta;
	private List<ProcesoLog> procesoLogList;

	private String stDescEstadoProceso;
	
	public ProcesoCarga() {
	}

	public ProcesoCarga(Integer cdIdproceso) {
		this.cdIdproceso = cdIdproceso;
	}

	public ProcesoCarga(Integer cdIdproceso, Date fhFecIni,
			Date fhFecFin, BigDecimal nrRegLeido, BigDecimal nrRegErrado,
			String stEstadoProceso, String stEstado, Date fhFecCreacion,
			String cdUsuCreacion, Date fhFecModifica, String cdUsuModifica,
			Date fhFecElimina, String cdUsuElimina, Date fhFecImporta,
			List<ProcesoLog> procesoLogList) {
		this.cdIdproceso = cdIdproceso;
		this.fhFecIni = fhFecIni;
		this.fhFecFin = fhFecFin;
		this.nrRegLeido = nrRegLeido;
		this.nrRegErrado = nrRegErrado;
		this.stEstadoProceso = stEstadoProceso;
		this.stEstado = stEstado;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
		this.fhFecImporta = fhFecImporta;
		this.procesoLogList = procesoLogList;
	}

	@Id
	@SequenceGenerator(name = "secProcesoCarga", sequenceName = "BBVATESOR.SEQ_PROCESOCARGA", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "secProcesoCarga")
	@Column(name = "CD_IDPROCESO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCdIdproceso() {
		return this.cdIdproceso;
	}

	public void setCdIdproceso(Integer cdIdproceso) {
		this.cdIdproceso = cdIdproceso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_FEC_INI", length = 7)
	public Date getFhFecIni() {
		return this.fhFecIni;
	}

	public void setFhFecIni(Date fhFecIni) {
		this.fhFecIni = fhFecIni;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_FEC_FIN", length = 7)
	public Date getFhFecFin() {
		return this.fhFecFin;
	}

	public void setFhFecFin(Date fhFecFin) {
		this.fhFecFin = fhFecFin;
	}

	@Column(name = "NR_REG_LEIDO", precision = 22, scale = 0)
	public BigDecimal getNrRegLeido() {
		return this.nrRegLeido;
	}

	public void setNrRegLeido(BigDecimal nrRegLeido) {
		this.nrRegLeido = nrRegLeido;
	}

	@Column(name = "NR_REG_ERRADO", precision = 22, scale = 0)
	public BigDecimal getNrRegErrado() {
		return this.nrRegErrado;
	}

	public void setNrRegErrado(BigDecimal nrRegErrado) {
		this.nrRegErrado = nrRegErrado;
	}

	@Column(name = "ST_ESTADO_PROCESO", length = 2)
	public String getStEstadoProceso() {
		return this.stEstadoProceso;
	}

	public void setStEstadoProceso(String stEstadoProceso) {
		this.stEstadoProceso = stEstadoProceso;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public String getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(String stEstado) {
		this.stEstado = stEstado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_FEC_IMPORTA", length = 7)
	public Date getFhFecImporta() {
		return this.fhFecImporta;
	}

	public void setFhFecImporta(Date fhFecImporta) {
		this.fhFecImporta = fhFecImporta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ProcesoCarga")
	public List<ProcesoLog> getProcesoLogList() {
		return procesoLogList;
	}

	public void setProcesoLogList(List<ProcesoLog> procesoLogList) {
		this.procesoLogList = procesoLogList;
	}
	
	@Transient
	public String getStDescEstadoProceso() {
		if (stEstadoProceso!=null){
			if(stEstadoProceso.equals("P"))stDescEstadoProceso="En Proceso";
			else if(stEstadoProceso.equals("T"))stDescEstadoProceso="Terminado";
			else if(stEstadoProceso.equals("E"))stDescEstadoProceso="Errado";
		}
		return stDescEstadoProceso;
	}

	public void setStDescEstadoProceso(String stDescEstadoProceso) {
		this.stDescEstadoProceso = stDescEstadoProceso;
	}


}
