package com.pss.simulador.bs.domain;
// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tsi001Saldo generated by hbm2java
 */
@Entity
@Table(name = "TSI001_SALDO")
public class Saldo implements java.io.Serializable {

	private BigDecimal cdIdsaldo;
	private String cdCodFondo;
	private String nbNomFondo;
	private String tpTipmoneda;
	private String nuNumCuenta;
	private BigDecimal toSaldoInicial;
	private BigDecimal imDifRescate;
	private BigDecimal imSuscripcion;
	private BigDecimal imRescate;
	private BigDecimal imVencimiento;
	private BigDecimal imComprasTmasn;
	private BigDecimal imVentasTmasn;
	private BigDecimal imCompra;
	private BigDecimal imVenta;
	private BigDecimal imCxpAcciones;
	private BigDecimal imCxcAcciones;
	private BigDecimal imComision;
	private BigDecimal toSaldoFinal;
	private BigDecimal imRescateTmasn;
	private BigDecimal imCarteTmenosuno;
	private BigDecimal imPorcLiquidez;
	private BigDecimal toSaldoInvertir;
	private String nbObservacion;
	private BigDecimal pcPorcPatrimonio;
	private BigDecimal imPatMonFondo;
	private BigDecimal pcPorcPatTot;
	private BigDecimal pcPorcContinenta;
	private BigDecimal pcPorcTotal;
	private BigDecimal imMtoExceso;
	private BigDecimal pcPorcAcciones;
	private BigDecimal imVinculado;
	private BigDecimal imLiquidezInmedi;
	private BigDecimal imSolicitudSusc;
	private BigDecimal imSolicitudResc;
	private BigDecimal imCxpPendiente;
	private BigDecimal imSaldoTmasn;

	public Saldo() {
	}

	public Saldo(BigDecimal cdIdsaldo) {
		this.cdIdsaldo = cdIdsaldo;
	}

	public Saldo(BigDecimal cdIdsaldo, String cdCodFondo,
			String nbNomFondo, String tpTipmoneda, String nuNumCuenta,
			BigDecimal toSaldoInicial, BigDecimal imDifRescate,
			BigDecimal imSuscripcion, BigDecimal imRescate,
			BigDecimal imVencimiento, BigDecimal imComprasTmasn,
			BigDecimal imVentasTmasn, BigDecimal imCompra, BigDecimal imVenta,
			BigDecimal imCxpAcciones, BigDecimal imCxcAcciones,
			BigDecimal imComision, BigDecimal toSaldoFinal,
			BigDecimal imRescateTmasn, BigDecimal imCarteTmenosuno,
			BigDecimal imPorcLiquidez, BigDecimal toSaldoInvertir,
			String nbObservacion, BigDecimal pcPorcPatrimonio,
			BigDecimal imPatMonFondo, BigDecimal pcPorcPatTot,
			BigDecimal pcPorcContinenta, BigDecimal pcPorcTotal,
			BigDecimal imMtoExceso, BigDecimal pcPorcAcciones,
			BigDecimal imVinculado, BigDecimal imLiquidezInmedi,
			BigDecimal imSolicitudSusc, BigDecimal imSolicitudResc,
			BigDecimal imCxpPendiente, BigDecimal imSaldoTmasn) {
		this.cdIdsaldo = cdIdsaldo;
		this.cdCodFondo = cdCodFondo;
		this.nbNomFondo = nbNomFondo;
		this.tpTipmoneda = tpTipmoneda;
		this.nuNumCuenta = nuNumCuenta;
		this.toSaldoInicial = toSaldoInicial;
		this.imDifRescate = imDifRescate;
		this.imSuscripcion = imSuscripcion;
		this.imRescate = imRescate;
		this.imVencimiento = imVencimiento;
		this.imComprasTmasn = imComprasTmasn;
		this.imVentasTmasn = imVentasTmasn;
		this.imCompra = imCompra;
		this.imVenta = imVenta;
		this.imCxpAcciones = imCxpAcciones;
		this.imCxcAcciones = imCxcAcciones;
		this.imComision = imComision;
		this.toSaldoFinal = toSaldoFinal;
		this.imRescateTmasn = imRescateTmasn;
		this.imCarteTmenosuno = imCarteTmenosuno;
		this.imPorcLiquidez = imPorcLiquidez;
		this.toSaldoInvertir = toSaldoInvertir;
		this.nbObservacion = nbObservacion;
		this.pcPorcPatrimonio = pcPorcPatrimonio;
		this.imPatMonFondo = imPatMonFondo;
		this.pcPorcPatTot = pcPorcPatTot;
		this.pcPorcContinenta = pcPorcContinenta;
		this.pcPorcTotal = pcPorcTotal;
		this.imMtoExceso = imMtoExceso;
		this.pcPorcAcciones = pcPorcAcciones;
		this.imVinculado = imVinculado;
		this.imLiquidezInmedi = imLiquidezInmedi;
		this.imSolicitudSusc = imSolicitudSusc;
		this.imSolicitudResc = imSolicitudResc;
		this.imCxpPendiente = imCxpPendiente;
		this.imSaldoTmasn = imSaldoTmasn;
	}

	@Id
	@Column(name = "CD_IDSALDO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdsaldo() {
		return this.cdIdsaldo;
	}

	public void setCdIdsaldo(BigDecimal cdIdsaldo) {
		this.cdIdsaldo = cdIdsaldo;
	}

	@Column(name = "CD_COD_FONDO", length = 4)
	public String getCdCodFondo() {
		return this.cdCodFondo;
	}

	public void setCdCodFondo(String cdCodFondo) {
		this.cdCodFondo = cdCodFondo;
	}

	@Column(name = "NB_NOM_FONDO", length = 40)
	public String getNbNomFondo() {
		return this.nbNomFondo;
	}

	public void setNbNomFondo(String nbNomFondo) {
		this.nbNomFondo = nbNomFondo;
	}

	@Column(name = "TP_TIPMONEDA", length = 3)
	public String getTpTipmoneda() {
		return this.tpTipmoneda;
	}

	public void setTpTipmoneda(String tpTipmoneda) {
		this.tpTipmoneda = tpTipmoneda;
	}

	@Column(name = "NU_NUM_CUENTA", length = 21)
	public String getNuNumCuenta() {
		return this.nuNumCuenta;
	}

	public void setNuNumCuenta(String nuNumCuenta) {
		this.nuNumCuenta = nuNumCuenta;
	}

	@Column(name = "TO_SALDO_INICIAL", precision = 22, scale = 0)
	public BigDecimal getToSaldoInicial() {
		return this.toSaldoInicial;
	}

	public void setToSaldoInicial(BigDecimal toSaldoInicial) {
		this.toSaldoInicial = toSaldoInicial;
	}

	@Column(name = "IM_DIF_RESCATE", precision = 22, scale = 0)
	public BigDecimal getImDifRescate() {
		return this.imDifRescate;
	}

	public void setImDifRescate(BigDecimal imDifRescate) {
		this.imDifRescate = imDifRescate;
	}

	@Column(name = "IM_SUSCRIPCION", precision = 22, scale = 0)
	public BigDecimal getImSuscripcion() {
		return this.imSuscripcion;
	}

	public void setImSuscripcion(BigDecimal imSuscripcion) {
		this.imSuscripcion = imSuscripcion;
	}

	@Column(name = "IM_RESCATE", precision = 22, scale = 0)
	public BigDecimal getImRescate() {
		return this.imRescate;
	}

	public void setImRescate(BigDecimal imRescate) {
		this.imRescate = imRescate;
	}

	@Column(name = "IM_VENCIMIENTO", precision = 22, scale = 0)
	public BigDecimal getImVencimiento() {
		return this.imVencimiento;
	}

	public void setImVencimiento(BigDecimal imVencimiento) {
		this.imVencimiento = imVencimiento;
	}

	@Column(name = "IM_COMPRAS_TMASN", precision = 22, scale = 0)
	public BigDecimal getImComprasTmasn() {
		return this.imComprasTmasn;
	}

	public void setImComprasTmasn(BigDecimal imComprasTmasn) {
		this.imComprasTmasn = imComprasTmasn;
	}

	@Column(name = "IM_VENTAS_TMASN", precision = 22, scale = 0)
	public BigDecimal getImVentasTmasn() {
		return this.imVentasTmasn;
	}

	public void setImVentasTmasn(BigDecimal imVentasTmasn) {
		this.imVentasTmasn = imVentasTmasn;
	}

	@Column(name = "IM_COMPRA", precision = 22, scale = 0)
	public BigDecimal getImCompra() {
		return this.imCompra;
	}

	public void setImCompra(BigDecimal imCompra) {
		this.imCompra = imCompra;
	}

	@Column(name = "IM_VENTA", precision = 22, scale = 0)
	public BigDecimal getImVenta() {
		return this.imVenta;
	}

	public void setImVenta(BigDecimal imVenta) {
		this.imVenta = imVenta;
	}

	@Column(name = "IM_CXP_ACCIONES", precision = 22, scale = 0)
	public BigDecimal getImCxpAcciones() {
		return this.imCxpAcciones;
	}

	public void setImCxpAcciones(BigDecimal imCxpAcciones) {
		this.imCxpAcciones = imCxpAcciones;
	}

	@Column(name = "IM_CXC_ACCIONES", precision = 22, scale = 0)
	public BigDecimal getImCxcAcciones() {
		return this.imCxcAcciones;
	}

	public void setImCxcAcciones(BigDecimal imCxcAcciones) {
		this.imCxcAcciones = imCxcAcciones;
	}

	@Column(name = "IM_COMISION", precision = 22, scale = 0)
	public BigDecimal getImComision() {
		return this.imComision;
	}

	public void setImComision(BigDecimal imComision) {
		this.imComision = imComision;
	}

	@Column(name = "TO_SALDO_FINAL", precision = 22, scale = 0)
	public BigDecimal getToSaldoFinal() {
		return this.toSaldoFinal;
	}

	public void setToSaldoFinal(BigDecimal toSaldoFinal) {
		this.toSaldoFinal = toSaldoFinal;
	}

	@Column(name = "IM_RESCATE_TMASN", precision = 22, scale = 0)
	public BigDecimal getImRescateTmasn() {
		return this.imRescateTmasn;
	}

	public void setImRescateTmasn(BigDecimal imRescateTmasn) {
		this.imRescateTmasn = imRescateTmasn;
	}

	@Column(name = "IM_CARTE_TMENOSUNO", precision = 22, scale = 0)
	public BigDecimal getImCarteTmenosuno() {
		return this.imCarteTmenosuno;
	}

	public void setImCarteTmenosuno(BigDecimal imCarteTmenosuno) {
		this.imCarteTmenosuno = imCarteTmenosuno;
	}

	@Column(name = "IM_PORC_LIQUIDEZ", precision = 22, scale = 0)
	public BigDecimal getImPorcLiquidez() {
		return this.imPorcLiquidez;
	}

	public void setImPorcLiquidez(BigDecimal imPorcLiquidez) {
		this.imPorcLiquidez = imPorcLiquidez;
	}

	@Column(name = "TO_SALDO_INVERTIR", precision = 22, scale = 0)
	public BigDecimal getToSaldoInvertir() {
		return this.toSaldoInvertir;
	}

	public void setToSaldoInvertir(BigDecimal toSaldoInvertir) {
		this.toSaldoInvertir = toSaldoInvertir;
	}

	@Column(name = "NB_OBSERVACION", length = 100)
	public String getNbObservacion() {
		return this.nbObservacion;
	}

	public void setNbObservacion(String nbObservacion) {
		this.nbObservacion = nbObservacion;
	}

	@Column(name = "PC_PORC_PATRIMONIO", precision = 22, scale = 0)
	public BigDecimal getPcPorcPatrimonio() {
		return this.pcPorcPatrimonio;
	}

	public void setPcPorcPatrimonio(BigDecimal pcPorcPatrimonio) {
		this.pcPorcPatrimonio = pcPorcPatrimonio;
	}

	@Column(name = "IM_PAT_MON_FONDO", precision = 22, scale = 0)
	public BigDecimal getImPatMonFondo() {
		return this.imPatMonFondo;
	}

	public void setImPatMonFondo(BigDecimal imPatMonFondo) {
		this.imPatMonFondo = imPatMonFondo;
	}

	@Column(name = "PC_PORC_PAT_TOT", precision = 22, scale = 0)
	public BigDecimal getPcPorcPatTot() {
		return this.pcPorcPatTot;
	}

	public void setPcPorcPatTot(BigDecimal pcPorcPatTot) {
		this.pcPorcPatTot = pcPorcPatTot;
	}

	@Column(name = "PC_PORC_CONTINENTA", precision = 22, scale = 0)
	public BigDecimal getPcPorcContinenta() {
		return this.pcPorcContinenta;
	}

	public void setPcPorcContinenta(BigDecimal pcPorcContinenta) {
		this.pcPorcContinenta = pcPorcContinenta;
	}

	@Column(name = "PC_PORC_TOTAL", precision = 22, scale = 0)
	public BigDecimal getPcPorcTotal() {
		return this.pcPorcTotal;
	}

	public void setPcPorcTotal(BigDecimal pcPorcTotal) {
		this.pcPorcTotal = pcPorcTotal;
	}

	@Column(name = "IM_MTO_EXCESO", precision = 22, scale = 0)
	public BigDecimal getImMtoExceso() {
		return this.imMtoExceso;
	}

	public void setImMtoExceso(BigDecimal imMtoExceso) {
		this.imMtoExceso = imMtoExceso;
	}

	@Column(name = "PC_PORC_ACCIONES", precision = 22, scale = 0)
	public BigDecimal getPcPorcAcciones() {
		return this.pcPorcAcciones;
	}

	public void setPcPorcAcciones(BigDecimal pcPorcAcciones) {
		this.pcPorcAcciones = pcPorcAcciones;
	}

	@Column(name = "IM_VINCULADO", precision = 22, scale = 0)
	public BigDecimal getImVinculado() {
		return this.imVinculado;
	}

	public void setImVinculado(BigDecimal imVinculado) {
		this.imVinculado = imVinculado;
	}

	@Column(name = "IM_LIQUIDEZ_INMEDI", precision = 22, scale = 0)
	public BigDecimal getImLiquidezInmedi() {
		return this.imLiquidezInmedi;
	}

	public void setImLiquidezInmedi(BigDecimal imLiquidezInmedi) {
		this.imLiquidezInmedi = imLiquidezInmedi;
	}

	@Column(name = "IM_SOLICITUD_SUSC", precision = 22, scale = 0)
	public BigDecimal getImSolicitudSusc() {
		return this.imSolicitudSusc;
	}

	public void setImSolicitudSusc(BigDecimal imSolicitudSusc) {
		this.imSolicitudSusc = imSolicitudSusc;
	}

	@Column(name = "IM_SOLICITUD_RESC", precision = 22, scale = 0)
	public BigDecimal getImSolicitudResc() {
		return this.imSolicitudResc;
	}

	public void setImSolicitudResc(BigDecimal imSolicitudResc) {
		this.imSolicitudResc = imSolicitudResc;
	}

	@Column(name = "IM_CXP_PENDIENTE", precision = 22, scale = 0)
	public BigDecimal getImCxpPendiente() {
		return this.imCxpPendiente;
	}

	public void setImCxpPendiente(BigDecimal imCxpPendiente) {
		this.imCxpPendiente = imCxpPendiente;
	}

	@Column(name = "IM_SALDO_TMASN", precision = 22, scale = 0)
	public BigDecimal getImSaldoTmasn() {
		return this.imSaldoTmasn;
	}

	public void setImSaldoTmasn(BigDecimal imSaldoTmasn) {
		this.imSaldoTmasn = imSaldoTmasn;
	}

}
