package com.pss.simulador.bs.domain;
// default package
// Generated 16/01/2016 12:44:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tsi004Tipocambio generated by hbm2java
 */
@Entity
@Table(name = "TSI004_TIPOCAMBIO")
public class TipoCambio implements java.io.Serializable {

	private BigDecimal cdIdtipocambio;
	private Date fhFecIngreso;
	private BigDecimal nuValor;
	private Date fhFecCreacion;
	private String cdUsuCreacion;
	private Date fhFecModifica;
	private String cdUsuModifica;
	private Date fhFecElimina;
	private String cdUsuElimina;
	private Character stEstado;

	public TipoCambio() {
	}

	public TipoCambio(BigDecimal cdIdtipocambio) {
		this.cdIdtipocambio = cdIdtipocambio;
	}

	public TipoCambio(BigDecimal cdIdtipocambio, Date fhFecIngreso,
			BigDecimal nuValor, Date fhFecCreacion, String cdUsuCreacion,
			Date fhFecModifica, String cdUsuModifica, Date fhFecElimina,
			String cdUsuElimina, Character stEstado) {
		this.cdIdtipocambio = cdIdtipocambio;
		this.fhFecIngreso = fhFecIngreso;
		this.nuValor = nuValor;
		this.fhFecCreacion = fhFecCreacion;
		this.cdUsuCreacion = cdUsuCreacion;
		this.fhFecModifica = fhFecModifica;
		this.cdUsuModifica = cdUsuModifica;
		this.fhFecElimina = fhFecElimina;
		this.cdUsuElimina = cdUsuElimina;
		this.stEstado = stEstado;
	}

	@Id
	@Column(name = "CD_IDTIPOCAMBIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdIdtipocambio() {
		return this.cdIdtipocambio;
	}

	public void setCdIdtipocambio(BigDecimal cdIdtipocambio) {
		this.cdIdtipocambio = cdIdtipocambio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_INGRESO", length = 7)
	public Date getFhFecIngreso() {
		return this.fhFecIngreso;
	}

	public void setFhFecIngreso(Date fhFecIngreso) {
		this.fhFecIngreso = fhFecIngreso;
	}

	@Column(name = "NU_VALOR", precision = 22, scale = 0)
	public BigDecimal getNuValor() {
		return this.nuValor;
	}

	public void setNuValor(BigDecimal nuValor) {
		this.nuValor = nuValor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_CREACION", length = 7)
	public Date getFhFecCreacion() {
		return this.fhFecCreacion;
	}

	public void setFhFecCreacion(Date fhFecCreacion) {
		this.fhFecCreacion = fhFecCreacion;
	}

	@Column(name = "CD_USU_CREACION", length = 10)
	public String getCdUsuCreacion() {
		return this.cdUsuCreacion;
	}

	public void setCdUsuCreacion(String cdUsuCreacion) {
		this.cdUsuCreacion = cdUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_MODIFICA", length = 7)
	public Date getFhFecModifica() {
		return this.fhFecModifica;
	}

	public void setFhFecModifica(Date fhFecModifica) {
		this.fhFecModifica = fhFecModifica;
	}

	@Column(name = "CD_USU_MODIFICA", length = 10)
	public String getCdUsuModifica() {
		return this.cdUsuModifica;
	}

	public void setCdUsuModifica(String cdUsuModifica) {
		this.cdUsuModifica = cdUsuModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_FEC_ELIMINA", length = 7)
	public Date getFhFecElimina() {
		return this.fhFecElimina;
	}

	public void setFhFecElimina(Date fhFecElimina) {
		this.fhFecElimina = fhFecElimina;
	}

	@Column(name = "CD_USU_ELIMINA", length = 10)
	public String getCdUsuElimina() {
		return this.cdUsuElimina;
	}

	public void setCdUsuElimina(String cdUsuElimina) {
		this.cdUsuElimina = cdUsuElimina;
	}

	@Column(name = "ST_ESTADO", length = 1)
	public Character getStEstado() {
		return this.stEstado;
	}

	public void setStEstado(Character stEstado) {
		this.stEstado = stEstado;
	}

}
